version: "3.9"

networks:
  project:
    driver: bridge

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${PROJECT_DIR}/db/logs:/var/log/mysql
      - ${PROJECT_DIR}/db/lib:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - project

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ${PROJECT_DIR}/dancer:/var/www/app/dancer
    networks:
      - project

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ${PROJECT_DIR}/dancer/public:/var/www/app/dancer/public
      - ${PROJECT_DIR}/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - project