version: "3.9"

networks:
  project:
    driver: bridge

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${PROJECT_DIR}/db/logs:/var/log/mysql
      - ${PROJECT_DIR}/db/lib:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - project

  cpanm:
    build:
      context: ./cpanm
      dockerfile: Dockerfile 
    volumes:
      - ${PROJECT_DIR}/app:/var/www/app
      - ${PROJECT_DIR}/perl:/var/www/perl
    networks:
      - project     

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - cpanm
    volumes:
      - ${PROJECT_DIR}/app:/var/www/app
      - ${PROJECT_DIR}/perl:/var/www/perl
    networks:
      - project

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ${PROJECT_DIR}/app/public:/var/www/app/public
      - ${PROJECT_DIR}/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:80"
    networks:
      - project

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - project
